-- 001_data_sources.sql
-- Generated by scripts/prepare-db-seeds.ts — DO NOT EDIT MANUALLY

INSERT INTO data_sources (name, source_type, url, description, reliability_level, collected_at)
VALUES
  ('Safe Maps — Dataset Académico v1', 'simulated', NULL, 'Dataset inicial generado con valores académicos/estimados para prototipo.', 'simulada', '2024-01-01');
