-- 002_risk_model_versions.sql
-- Generated by scripts/prepare-db-seeds.ts — DO NOT EDIT MANUALLY

INSERT INTO risk_model_versions (code, name, description, formula, is_active)
VALUES
  ('euler-v1', 'Euler v1 — Modelo diferencial lineal', 'Integración numérica por método de Euler. dR/dx = a·C̃ − b·S̃ − d·Ṽ − e·Ĩ + h·F̃.', 'R(n+1) = clamp(R(n) + f(C,S,V,I,F) * Δx_km, 0, 100)', true);
