-- 003_communes.sql
-- Generated by scripts/prepare-db-seeds.ts — DO NOT EDIT MANUALLY
-- geometry column is intentionally omitted here.
-- Load geometry separately with a GeoJSON import script using ST_GeomFromGeoJSON().

INSERT INTO communes (zona_id, comuna_numero, name)
VALUES
  ('comuna_01', 1, 'Comuna 1'),
  ('comuna_02', 2, 'Comuna 2'),
  ('comuna_03', 3, 'Comuna 3'),
  ('comuna_04', 4, 'Comuna 4'),
  ('comuna_05', 5, 'Comuna 5'),
  ('comuna_06', 6, 'Comuna 6'),
  ('comuna_07', 7, 'Comuna 7'),
  ('comuna_08', 8, 'Comuna 8'),
  ('comuna_09', 9, 'Comuna 9'),
  ('comuna_10', 10, 'Comuna 10'),
  ('comuna_11', 11, 'Comuna 11'),
  ('comuna_12', 12, 'Comuna 12'),
  ('comuna_13', 13, 'Comuna 13'),
  ('comuna_14', 14, 'Comuna 14'),
  ('comuna_15', 15, 'Comuna 15'),
  ('comuna_16', 16, 'Comuna 16'),
  ('comuna_17', 17, 'Comuna 17'),
  ('comuna_18', 18, 'Comuna 18'),
  ('comuna_19', 19, 'Comuna 19'),
  ('comuna_20', 20, 'Comuna 20'),
  ('comuna_21', 21, 'Comuna 21'),
  ('comuna_22', 22, 'Comuna 22');
