-- 004_risk_model_coefficients.sql
-- Generated by scripts/prepare-db-seeds.ts — DO NOT EDIT MANUALLY

INSERT INTO risk_model_coefficients (model_version_id, variable_code, variable_name, coefficient, effect_direction)
VALUES
  ((SELECT id FROM risk_model_versions WHERE code = 'euler-v1'), 'C', 'criminalidad', 30, 'increase'),
  ((SELECT id FROM risk_model_versions WHERE code = 'euler-v1'), 'S', 'seguridad', 15, 'decrease'),
  ((SELECT id FROM risk_model_versions WHERE code = 'euler-v1'), 'V', 'vigilancia', 10, 'decrease'),
  ((SELECT id FROM risk_model_versions WHERE code = 'euler-v1'), 'I', 'iluminacion', 10, 'decrease'),
  ((SELECT id FROM risk_model_versions WHERE code = 'euler-v1'), 'F', 'flujo_personas', 8, 'increase');
