-- 005_commune_risk_profiles.sql
-- Generated by scripts/prepare-db-seeds.ts — DO NOT EDIT MANUALLY
-- Variables transformed from 0–10 to 0–100 scale (×10).

INSERT INTO commune_risk_profiles
  (commune_id, model_version_id, valid_from, valid_to,
   criminalidad, seguridad, vigilancia, iluminacion, flujo_personas,
   risk_score, risk_level, data_quality, source_id)
VALUES
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_01'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    4.6, 48, 45, 42, 38,
    30.3, 'low', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_02'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    35.3, 78, 72, 82, 74,
    33.7, 'low', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_03'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    24.8, 52, 70, 75, 88,
    36.6, 'low', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_04'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    31.5, 58, 62, 68, 72,
    38.7, 'low', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_05'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    4.6, 68, 61, 72, 65,
    23.6, 'low', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_06'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    43.9, 46, 52, 58, 78,
    49.8, 'medium', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_07'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    37.1, 44, 54, 56, 76,
    46.8, 'medium', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_08'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    75.5, 50, 55, 62, 70,
    61.5, 'medium', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_09'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    39.3, 49, 64, 70, 82,
    44.5, 'medium', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_10'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    44, 58, 54, 57, 52,
    47, 'medium', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_11'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    48.2, 55, 56, 66, 68,
    47.5, 'medium', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_12'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    38.3, 54, 55, 65, 69,
    43.6, 'medium', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_13'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    69.2, 35, 48, 50, 80,
    64.9, 'medium', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_14'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    86.2, 29, 50, 48, 82,
    73.9, 'high', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_15'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    100, 25, 51, 52, 84,
    80.5, 'high', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_16'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    56.4, 57, 58, 68, 79,
    51.4, 'medium', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_17'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    13.8, 74, 70, 86, 95,
    26.8, 'low', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_18'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    83.8, 31, 50, 55, 75,
    71, 'high', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_19'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    16.5, 73, 74, 84, 92,
    27.5, 'low', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_20'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    41.6, 34, 47, 50, 58,
    50.7, 'medium', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_21'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    65.1, 38, 49, 50, 86,
    62.9, 'medium', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  ),
  (
    (SELECT id FROM communes WHERE zona_id = 'comuna_22'),
    (SELECT id FROM risk_model_versions WHERE code = 'euler-v1'),
    '2024-01-01', NULL,
    25, 85, 68, 88, 62,
    26.5, 'low', 'simulated',
    (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')
  );
