-- 007_risk_time_windows.sql
-- Generated by scripts/prepare-db-seeds.ts — DO NOT EDIT MANUALLY

INSERT INTO risk_time_windows
  (horario_id, label, start_time, end_time,
   homicidios_2024, homicidios_2025, variation_absolute, variation_pct,
   risk_score, risk_level, source_id)
VALUES
  ('h01', '00:00–02:59', '00:00', '02:59', 133, 187, 54, 0.406, 7.31, 'ALTO', (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')),
  ('h02', '03:00–05:59', '03:00', '05:59', 87, 82, -5, -0.0575, 0.58, 'BAJO', (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')),
  ('h03', '06:00–08:59', '06:00', '08:59', 57, 74, 17, 0.2982, 0.06, 'BAJO', (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')),
  ('h04', '09:00–11:59', '09:00', '11:59', 53, 73, 20, 0.3774, 0, 'BAJO', (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')),
  ('h05', '12:00–14:59', '12:00', '14:59', 119, 102, -17, -0.1429, 1.86, 'BAJO', (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')),
  ('h06', '15:00–17:59', '15:00', '17:59', 113, 118, 5, 0.0442, 2.88, 'MEDIO', (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')),
  ('h07', '18:00–20:59', '18:00', '20:59', 181, 193, 12, 0.0663, 7.69, 'ALTO', (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1')),
  ('h08', '21:00–23:59', '21:00', '23:59', 195, 229, 34, 0.1744, 10, 'ALTO', (SELECT id FROM data_sources WHERE name = 'Safe Maps — Dataset Académico v1'));
