#!/usr/bin/env tsx
/**
 * prepare-commune-geometry-seed.ts
 *
 * Reads apps/web/public/data/comunas-cali.geojson and generates:
 *   data/processed/commune_geometries.json  — intermediate metadata + geometry
 *   data/seeds/008_commune_geometries.sql   — PostGIS UPDATE statements
 *
 * Run:
 *   npm run prepare-geometry-seed
 *
 * Prerequisites for applying the SQL:
 *   - PostGIS extension active (CREATE EXTENSION postgis)
 *   - communes table populated (seeds 001–003 applied)
 */

import * as fs from "node:fs";
import * as path from "node:path";

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const ROOT          = path.resolve(__dirname, "..");
const GEOJSON_PATH  = path.join(ROOT, "apps", "web", "public", "data", "comunas-cali.geojson");
const PROCESSED_DIR = path.join(ROOT, "data", "processed");
const SEEDS_DIR     = path.join(ROOT, "data", "seeds");

const GEOMETRY_SOURCE = "IDESC/QGIS GeoJSON EPSG:4326";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface GeoJSONGeometry {
  type: "Polygon" | "MultiPolygon";
  coordinates: unknown;
}

interface RawFeatureProperties {
  comuna: number;
  nombre: string;
  [key: string]: unknown;
}

interface RawFeature {
  type: "Feature";
  properties: RawFeatureProperties;
  geometry: GeoJSONGeometry;
}

interface RawGeoJSON {
  type: "FeatureCollection";
  features: RawFeature[];
}

interface CommuneGeometryRecord {
  comuna_numero: number;
  nombre: string;
  geometry_type: "Polygon" | "MultiPolygon";
  geometry_source: string;
  geometry: GeoJSONGeometry;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function escapeSQL(str: string): string {
  return `'${str.replace(/'/g, "''")}'`;
}

function validate(features: RawFeature[]): void {
  if (features.length !== 22) {
    throw new Error(`Expected 22 features, got ${features.length}`);
  }

  const nums = features.map((f) => f.properties.comuna).sort((a, b) => a - b);
  const expected = Array.from({ length: 22 }, (_, i) => i + 1);
  const missing = expected.filter((n) => !nums.includes(n));
  const dupes = nums.filter((n, i) => nums.indexOf(n) !== i);

  if (missing.length > 0) throw new Error(`Missing comuna_numero: ${missing.join(", ")}`);
  if (dupes.length > 0)   throw new Error(`Duplicate comuna_numero: ${dupes.join(", ")}`);

  for (const f of features) {
    if (f.geometry.type !== "Polygon" && f.geometry.type !== "MultiPolygon") {
      throw new Error(
        `Feature ${f.properties.comuna}: unsupported geometry type "${f.geometry.type}"`
      );
    }
  }
}

// ---------------------------------------------------------------------------
// SQL generation
// ---------------------------------------------------------------------------

function buildSQL(sorted: RawFeature[]): string {
  const lines: string[] = [
    "-- 008_commune_geometries.sql",
    "-- Updates communes.geometry from IDESC GeoJSON (EPSG:4326)",
    "-- Generated by scripts/prepare-commune-geometry-seed.ts",
    "--",
    "-- Prerequisites:",
    "--   1. PostGIS extension active (CREATE EXTENSION IF NOT EXISTS postgis)",
    "--   2. Supabase migration applied (supabase/migrations/20260514_initial_schema.sql)",
    "--   3. Seeds 001–007 applied (communes table must be populated)",
    `-- Generated: ${new Date().toISOString()}`,
    "",
    "BEGIN;",
    "",
  ];

  for (const feature of sorted) {
    const comunaNum = feature.properties.comuna;
    const nombre    = feature.properties.nombre;
    const geomJson  = JSON.stringify(feature.geometry).replace(/'/g, "''");

    // Wrap in ST_Multi() — no-op for MultiPolygon, promotes Polygon to MultiPolygon
    lines.push(`-- ${nombre} (comuna_numero = ${comunaNum})`);
    lines.push(`UPDATE communes`);
    lines.push(`SET`);
    lines.push(`  geometry        = ST_Multi(ST_SetSRID(ST_GeomFromGeoJSON('${geomJson}'), 4326)),`);
    lines.push(`  geometry_source = ${escapeSQL(GEOMETRY_SOURCE)},`);
    lines.push(`  updated_at      = now()`);
    lines.push(`WHERE comuna_numero = ${comunaNum};`);
    lines.push("");
  }

  lines.push("COMMIT;");
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  console.log("Safe Maps — Commune Geometry Seed Preparation\n");

  // Read GeoJSON
  if (!fs.existsSync(GEOJSON_PATH)) {
    throw new Error(
      `GeoJSON file not found: ${GEOJSON_PATH}\n` +
      `Expected at: apps/web/public/data/comunas-cali.geojson`
    );
  }

  const geo = JSON.parse(fs.readFileSync(GEOJSON_PATH, "utf-8")) as RawGeoJSON;
  console.log(`  → Loaded ${geo.features.length} features from comunas-cali.geojson`);

  validate(geo.features);
  console.log(`  ✓ Validation passed: 22 comunas, all 1–22, no duplicates\n`);

  // Sort by comuna_numero for deterministic output
  const sorted = [...geo.features].sort(
    (a, b) => a.properties.comuna - b.properties.comuna
  );

  // Build processed records (metadata + geometry for downstream validation)
  const processed: CommuneGeometryRecord[] = sorted.map((f) => ({
    comuna_numero:   f.properties.comuna,
    nombre:          f.properties.nombre,
    geometry_type:   f.geometry.type,
    geometry_source: GEOMETRY_SOURCE,
    geometry:        f.geometry,
  }));

  // Ensure output dirs exist
  fs.mkdirSync(PROCESSED_DIR, { recursive: true });
  fs.mkdirSync(SEEDS_DIR, { recursive: true });

  // Write processed JSON
  const jsonPath = path.join(PROCESSED_DIR, "commune_geometries.json");
  fs.writeFileSync(jsonPath, JSON.stringify(processed, null, 2), "utf-8");
  console.log(`  ✓ Written: data/processed/commune_geometries.json  (${processed.length} records)`);

  // Write SQL seed
  const sqlPath = path.join(SEEDS_DIR, "008_commune_geometries.sql");
  fs.writeFileSync(sqlPath, buildSQL(sorted), "utf-8");
  console.log(`  ✓ Written: data/seeds/008_commune_geometries.sql   (${sorted.length} UPDATE statements)`);

  console.log("\n✓ Geometry seed complete.");
  console.log("  Next: apply supabase/migrations/ then seeds 001–008 in order.");
}

main();
